spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/sys?characterEncoding=UTF-8&allowMultiQueries=true&useTimezone=true&serverTimezone=Asia/Kuala_Lumpur
  username: root
  password: alpha_D$N
  #username: root
  #password:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  minIdle: 1
  hikari:
   connectionTimeout: 30000
   idleTimeout: 600000
   maxLifetime: 1800000
   maximumPoolSize: 50
   minimumIdle: 10
   validationTimeout: 5000

server:
   port: 8080

activemq:
  broker-url: failover:(tcp://192.168.0.15:61616,tcp://192.168.0.251:61616)?timeout=30000&randomize=true

spring:
  cron:
    expression:
#      appmonitoring: 0 */15 * ? * * # every 15min
#      masterFile: 0 */15 * ? * * # every 15mins
#      postingRecord: 0 */15 * ? * * # every 15mins
#      responseFile: 0 */15 * ? * * # every 15mins
#      refundProcess: 0 */15 * ? * * # every 15mins
#      refundTransaction: 0 */15 * ? * * # every 15mins
#      outwardTransaction: 0 */15 * ? * * # every 15mins
# ------------------- dev cron -------------------
#      appmonitoring: 0 0/1 * ? * * # every 1min
#      masterFile: 0 0/1 * ? * * # every 1min
#      postingRecord: 0 0/1 * ? * * # every 1min
#      responseFile: 0 0/1 * ? * * # every 1min
#      refundProcess: 0 0/1 * ? * * # every 1min
#      refundTransaction: 0 */1 * ? * * # every 1min
#      outwardTransaction: 0 */1 * ? * * # every 1min
       amqMonitoring: 0 */10 * ? * * # every 10min
  mail:
     host: smtp.gmail.com
     port: 587
     username: irppappmonitoring@gmail.com
     password: qbppuysnjpqugnln
     properties:
        mail:
           smtp:
             auth: true
             starttls:
                 enable: true

jasypt:
  encryptor:
    password: CAPKEY

retry:
  maxAttempts: 3
  delay: 5000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000000

appmonitor-api-service:
 ribbon:
  listOfServers: http://appmonitor-api:8080
  OkToRetryOnAllOperations: false

portal-api-service:
 ribbon:
  listOfServers: http://AdminBackend:8080/api
  OkToRetryOnAllOperations: false

ntf:
 enableEmail: true
 recipient:
  default: jyuan.fam@beans.com.my

Amq:
 URL:
   Primary: http://192.168.0.251:8161/
   Secondary: http://192.168.0.15:8161/
 mail:
   toEmail: baski.seagar@beans.com.my
   cc: bgbaski.seagar@gmail.com

