spring.datasource:
  url: jdbc:mysql://127.0.0.1:3306/sys?characterEncoding=UTF-8&allowMultiQueries=true&useTimezone=true&serverTimezone=Asia/Kuala_Lumpur
  username: root
  password: alpha_D$N
  #username: root
  #password:
  type: com.zaxxer.hikari.HikariDataSource
  driver-class-name: com.mysql.cj.jdbc.Driver
  maxActive: 20
  initialSize: 1
  maxWait: 60000
  timeBetweenEvictionRunsMillis: 60000
  minEvictableIdleTimeMillis: 300000
  minIdle: 1
  hikari:
   connectionTimeout: 30000
   idleTimeout: 600000
   maxLifetime: 1800000
   maximumPoolSize: 50
   minimumIdle: 10
   validationTimeout: 5000

server:
   port: 8081
   test: 0

activemq:
  broker-url: failover:(tcp://localhost:61616,tcp://localhost:61616)?timeout=30000&randomize=true

amq:
  name: USER_IN
